env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    no-dupe-else-if: 'off',
    no-import-assign: 'off',
    no-setter-return: 'off',
    react/jsx-uses-react: 'error',
    react/jsx-uses-vars: 'error',
  }
settings:
  react: { version: 'detect' }
